default:
	cc0 -x -o nocontractsbintest arrayutil.c0 binsearch.c0 bin-test.c0
	cc0 -x -d -o contractsbintest arrayutil.c0 binsearch.c0 bin-test.c0

clean:
	rm -f *~ nocontractsbintest contractsbintest
